title: product
'@extends': modular

form:
  fields:
    tabs:
      fields:
        content:
          fields:

            header.title:
              label: Name
              validate:
                required: true

            header.media_order:
              label: Images
              validate:
                required: true

            header.price:
              type: number
              label: Price
              help: The price of the product. Note that you must use a ```.``` as decimal separator.
              validate:
                required: true

            header.description:
              type: text
              label: Short Description
              validate:
                required: true
