title: product
'@extends': default

form:
  fields:
    tabs:
      fields:
        content:
          fields:

            section_product:
              type: section
              title: Product

            header.id:
              type: text
              label: Product ID
              validate:
                required: true

            header.image:
              type: filepicker
              label: Product Image
              preview_images: true
              validate:
                required: true
              accept:
                - .jpg

            header.price:
              type: text
              label: Price
              validate:
                required: true

            header.description:
              type: text
              label: Short Description
              validate:
                required: true

            section_modular:
              type: section
              title: Modular

            header.content.items:
              type: text
              label: PLUGIN_ADMIN.ITEMS
              default: '@self.modular'
              size: medium

            header.content.order.by:
              type: text
              label: PLUGIN_ADMIN.ORDER_BY
              placeholder: folder
              size: small

            header.content.order.dir:
              type: text
              label: PLUGIN_ADMIN.ORDER
              help: '"desc" or "asc" are valid values'
              placeholder: acs
              size: small
